apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slack-translation-bot-db
  namespace: slack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi