apiVersion: v1
kind: Service
metadata:
  name: slack-translation-bot
  namespace: slack
spec:
  type: NodePort
  selector:
    app: slack-translation-bot
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30101